#setwd("/home/cgeorges/Senior_Seminar/simulation73")
#df1 <- output2df("output73.rds")
#write.csv(df1, file = "sim73.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation74")
df1 <- output2df("output74.rds")
write.csv(df1, file = "sim74.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation75")
df1 <- output2df("output75.rds")
write.csv(df1, file = "sim75.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation76")
df1 <- output2df("output76.rds")
write.csv(df1, file = "sim76.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation77")
df1 <- output2df("output77.rds")
write.csv(df1, file = "sim77.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation78")
df1 <- output2df("output78.rds")
write.csv(df1, file = "sim78.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation79")
df1 <- output2df("output79.rds")
write.csv(df1, file = "sim79.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation80")
df1 <- output2df("output80.rds")
write.csv(df1, file = "sim80.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation81")
df1 <- output2df("output81.rds")
write.csv(df1, file = "sim81.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation82")
df1 <- output2df("output82.rds")
write.csv(df1, file = "sim82.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation83")
df1 <- output2df("output83.rds")
write.csv(df1, file = "sim83.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation84")
df1 <- output2df("output84.rds")
write.csv(df1, file = "sim84.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation85")
df1 <- output2df("output85.rds")
write.csv(df1, file = "sim85.csv")
setwd("/home/cgeorges/Senior_Seminar/simulation86")
df1 <- output2df("output86.rds")
write.csv(df1, file = "sim86.csv")
