#PBS -N riskmltest  
#PBS -l nodes=2:ppn=8    
#PBS -l mem=4GB 
#PBS -q una   
#PBS -M cgeorges@hamilton.edu 
#PBS -m bea        
#PBS -j oe         
#PBS -l walltime=00:20:00
#PBS -r y
#
cd $PBS_O_WORKDIR
#module load mpi/mvapich2-x86_64
#module load R/3.4.2
module load R/3.5.0	#7/7/18
module load openmpi/3.1.0   #7/6/18
export OMP_NUM_THREADS=1    #7/6/18 for openmpi
#rm ../output.rds
#rm riskmltest.o*

#Rscript montecarlo.r 
#mpirun -np 1 R --file=montecarlo-test.r   #7/6/18
#mpiexec -np 1 R --file=montecarlo-test.r   #7/7/18
mpiexec -np 1 R CMD BATCH ./montecarlo-test.r	#7/7//18
#Rscript montecarlo-test.r  #7/12/18

